tier: 6
checkpoints: [
  'chkpt/kss/kss_5c30182_tier1_000.pt',
  'chkpt/kss/kss_5c30182_tier2_000.pt',
  'chkpt/kss/kss_5c30182_tier3_000.pt',
  'chkpt/kss/kss_5c30182_tier4_000.pt',
  'chkpt/kss/kss_5c30182_tier5_000.pt',
  'chkpt/kss/kss_5c30182_tier6_000.pt',
]
conditional: True
