tier: 3
checkpoints: [
  'chkpt_3_tier/chkpt/blizzard-3-tier_t1/blizzard-3-tier_t1_ea11a84_tier1_001.pt',
  'chkpt_3_tier/chkpt/blizzard-3-tier_t2/blizzard-3-tier_t2_ea11a84_tier2_000.pt',
  'chkpt_3_tier/chkpt/blizzard-3-tier_t3/blizzard-3-tier_t3_ea11a84_tier3_004.pt',
]
conditional: True
